use_frameworks!

target 'DropdownAlert_Example' do
  pod 'DropdownAlert', :path => '../'

  target 'DropdownAlert_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
